name: evently_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  smooth_page_indicator: ^1.2.0+3
  animated_bottom_navigation_bar: ^1.3.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in:
  google_sign_in_android: 
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  lottie: ^3.2.0
  svg_flutter: 
  cloud_firestore: ^5.6.3
  intl_utils: ^2.8.10
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0


flutter:
  generate: true


  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  assets:
    - assets/icons/arrow_back_icon.png
    - assets/icons/arrow_front_icon.png
    - assets/icons/crying.json
    - assets/icons/eyeSlashIIcon.png
    - assets/icons/googleIcon.png
    - assets/icons/mailIcon.png
    - assets/icons/passIcon.png
    - assets/icons/personIcon.png
    - assets/icons/smile.json
    - assets/icons/themeMode.svg
    - assets/images/Eating.png
    - assets/images/Logo.png
    - assets/images/birthDayCard.png
    - assets/images/bookClubCard.png
    - assets/images/eventlyLogo.png
    - assets/images/exhbitionCard.png
    - assets/images/forget_pass.png
    - assets/images/gamingCard.png
    - assets/images/holidayCard.png
    - assets/images/meetingCard.png
    - assets/images/onBoarding1.png
    - assets/images/onBoarding2.png
    - assets/images/onBoarding3.png
    - assets/images/onBoardng4.png
    - assets/images/sportsCard.png
    - assets/images/workShopCard.png
  fonts:
    - family: Inter_18pt-Bold
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
    - family: Inter_18pt-BoldItalic
      fonts:
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
    - family: Inter_18pt-Medium
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
    - family: Inter_18pt-MediumItalic
      fonts:
        - asset: assets/fonts/Inter_18pt-MediumItalic.ttf
    - family: Inter_18pt-Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Inter_18pt-SemiBold
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
    - family: Inter_18pt-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBoldItalic.ttf

