/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'evently_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ARROW_BACK_ICON = 'assets/icons/arrow_back_icon.png';
  static const String ARROW_FRONT_ICON = 'assets/icons/arrow_front_icon.png';
  static const String CRYING = 'assets/icons/crying.json';
  static const String EYESLASHIICON = 'assets/icons/eyeSlashIIcon.png';
  static const String GOOGLEICON = 'assets/icons/googleIcon.png';
  static const String MAILICON = 'assets/icons/mailIcon.png';
  static const String PASSICON = 'assets/icons/passIcon.png';
  static const String PERSONICON = 'assets/icons/personIcon.png';
  static const String SMILE = 'assets/icons/smile.json';
  static const String THEMEMODE = 'assets/icons/themeMode.svg';
  static const String EATING = 'assets/images/Eating.png';
  static const String LOGO = 'assets/images/Logo.png';
  static const String BIRTHDAYCARD = 'assets/images/birthDayCard.png';
  static const String BOOKCLUBCARD = 'assets/images/bookClubCard.png';
  static const String EVENTLYLOGO = 'assets/images/eventlyLogo.png';
  static const String EXHBITIONCARD = 'assets/images/exhbitionCard.png';
  static const String FORGET_PASS = 'assets/images/forget_pass.png';
  static const String GAMINGCARD = 'assets/images/gamingCard.png';
  static const String HOLIDAYCARD = 'assets/images/holidayCard.png';
  static const String MEETINGCARD = 'assets/images/meetingCard.png';
  static const String ONBOARDING1 = 'assets/images/onBoarding1.png';
  static const String ONBOARDING2 = 'assets/images/onBoarding2.png';
  static const String ONBOARDING3 = 'assets/images/onBoarding3.png';
  static const String ONBOARDNG4 = 'assets/images/onBoardng4.png';
  static const String SPORTSCARD = 'assets/images/sportsCard.png';
  static const String WORKSHOPCARD = 'assets/images/workShopCard.png';
}
